version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo_db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /data/auth_db:/data/db
    ports:
      - 27017:27017